id: I43124364
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:22:56+00:00'
last_modified: '2022-06-09T06:14:46.955532+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30308
  title: སློབ་གྲྭ་ཆུང་འབྲིང་གི་སློབ་མའི་རྩོམ་ཡིག་སྦྱོང་བའི་མྱུར་ལམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '6748':
      image_group_id: I1PD30309
      title: Volume 1 of slob grwa chung 'bring gi slob ma'i rtsom yig sbyong ba'i
        myur lam
      total_pages: 168
      order: 1
      base_file: 6748.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
