id: P007125
initial_creation_type: ocr
source_metadata:
  id: bdr:W30308
  title: སློབ་གྲྭ་ཆུང་འབྲིང་གི་སློབ་མའི་རྩོམ་ཡིག་སྦྱོང་བའི་མྱུར་ལམ
  author: ''
  volumes:
    e672f163f05a4cecb80ca988cb7ed3ba:
      image_group_id: I1PD30309
      title: ''
      volume_number: 1
      total_pages: 168
ebook_metadata:
  title: སློབ་གྲྭ་ཆུང་འབྲིང་གི་སློབ་མའི་རྩོམ་ཡིག་སྦྱོང་བའི་མྱུར་ལམ
  author: ''
  sku: P007125
  cover: cover.jpg
  layers:
  - pagination
